# .streamlit/secrets.toml
tmdb_api_key = "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJmMWQ1MjE0NWZlYWI0NTFlMmMxMzMyZDA4ODAyZjQ2MCIsIm5iZiI6MTc0MjQ4ODk3Mi45NzUwMDAxLCJzdWIiOiI2N2RjNDU4YzE4NmVjYTU3YjJlN2MxNWIiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.11kwFgGOHsZl4xDmWS4V4MmpCoO3MkjhPVr4w7DWfNk"


#http://api.themoviedb.org/3/configuration?api_key=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJmMWQ1MjE0NWZlYWI0NTFlMmMxMzMyZDA4ODAyZjQ2MCIsIm5iZiI6MTc0MjQ4ODk3Mi45NzUwMDAxLCJzdWIiOiI2N2RjNDU4YzE4NmVjYTU3YjJlN2MxNWIiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.11kwFgGOHsZl4xDmWS4V4MmpCoO3MkjhPVr4w7DWfNk


omdb_api = "c20071fc"

gemini_api_key = "AIzaSyASZ8knN1xPZwQHT_EM7XuQ1QVgVH3fauU"